#!/usr/bin/env python3
"""Regenerate docs/atlas/records/_index.md.

The index is a browse view for a human, derived entirely from the store: the
titles are the menu, and the standing of each record — superseded, refuted,
answered — is computed from the typed edges pointing at it rather than read
from a field somebody had to remember to update.

Usage:
    reindex.py
"""
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import _lib  # noqa: E402
import links  # noqa: E402

TYPE_LABEL = {
    "memory": "Memory — constraints in force",
    "question": "Questions",
    "decision": "Decisions",
    "experiment": "Experiments",
}
TYPE_ORDER = ["memory", "question", "decision", "experiment"]


def build():
    _lib.require_version()
    records = _lib.load_all()
    mentions, edges, _ = links.graph(records)
    state = links.derive_state(records, edges)
    incoming = links.backlinks(mentions)

    by_type = defaultdict(list)
    for rid, rec in sorted(records.items()):
        by_type[rec.type].append(rec)

    lines = [
        "# Record Index",
        "",
        "> Auto-generated by reindex.py. Do not edit by hand.",
        "",
    ]

    for rtype in TYPE_ORDER + sorted(set(by_type) - set(TYPE_ORDER)):
        entries = by_type.get(rtype)
        if not entries:
            continue
        label = TYPE_LABEL.get(rtype, f"{rtype} (unknown type — fix it)")
        # Retired records sort last so the live ones read first.
        entries.sort(key=lambda r: (r.id in state, r.id))
        lines.append(f"## {label} ({len(entries)})")
        lines.append("")
        for rec in entries:
            line = f"- **{rec.id:03d}** [[{rec.stem}|{rec.title}]] — {rec.meta.get('date', '?')}"
            extras = []
            standing = state.get(rec.id)
            if standing:
                label_, sources = standing
                extras.append(f"{label_} by " + ", ".join(f"{s:03d}" for s in sources))
            tags = rec.meta.get("tags") or []
            if tags:
                extras.append("tags: " + ", ".join(tags))
            cited = incoming.get(rec.id) or []
            if cited:
                extras.append(f"cited by {len(cited)}")
            if extras:
                line += " — " + "; ".join(extras)
            lines.append(line)
        lines.append("")

    out = "\n".join(lines).rstrip() + "\n"
    _lib.RECORDS.mkdir(parents=True, exist_ok=True)
    _lib.atomic_write(_lib.RECORDS / "_index.md", out)
    print(f"reindexed {_lib.RECORDS}/_index.md ({len(records)} records)")


if __name__ == "__main__":
    build()
