#!/usr/bin/env python3
"""Regenerate _index.md for each entity directory.

Usage:
    reindex.py              # all three
    reindex.py --type D     # only decisions
"""
import argparse
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import _lib  # noqa: E402

TYPE_LABEL = {"D": "Decisions", "E": "Experiments", "Q": "Questions"}

STATUS_ORDER = {
    "D": ["active", "planned", "superseded", "rejected"],
    "E": ["running", "planned", "completed", "abandoned"],
    "Q": ["open", "answered", "merged-into-D", "wontfix"],
}


def build_index_for(type_letter):
    target_dir = _lib.ATLAS / _lib.TYPE_DIR[type_letter]
    if not target_dir.exists():
        return

    by_status = defaultdict(list)
    for p in sorted(target_dir.glob(f"{type_letter}-*.md")):
        meta, _ = _lib.parse_md(p.read_text(encoding="utf-8"))
        status = meta.get("status", "unknown")
        by_status[status].append((meta, p))

    lines = [
        f"# {TYPE_LABEL[type_letter]} Index",
        "",
        "> Auto-generated by reindex.py. Do not edit by hand.",
        "",
    ]

    seen = set()
    for status in STATUS_ORDER[type_letter]:
        if status not in by_status:
            continue
        seen.add(status)
        entries = by_status[status]
        lines.append(f"## {status} ({len(entries)})")
        lines.append("")
        for meta, _ in entries:
            line = (
                f"- **{meta.get('id')}** {meta.get('title', '(no title)')} "
                f"— {meta.get('date', '?')}"
            )
            extras = []
            tags = meta.get("tags") or []
            if tags:
                extras.append("tags: " + ", ".join(tags))
            if type_letter == "D":
                aff = meta.get("affects") or []
                if aff:
                    extras.append("affects: " + ", ".join(aff))
                sb = meta.get("superseded-by") or []
                if sb:
                    extras.append("superseded-by: " + ", ".join(sb))
            elif type_letter == "Q":
                if meta.get("answered-by"):
                    extras.append(f"answered-by: {meta['answered-by']}")
            if extras:
                line += " — " + "; ".join(extras)
            lines.append(line)
        lines.append("")

    for status in sorted(set(by_status) - seen):
        lines.append(f"## {status} (unknown — fix lifecycle)")
        for meta, _ in by_status[status]:
            lines.append(f"- {meta.get('id')} {meta.get('title')}")
        lines.append("")

    out = "\n".join(lines).rstrip() + "\n"
    (target_dir / "_index.md").write_text(out, encoding="utf-8")
    print(f"reindexed {target_dir}/_index.md ({sum(len(v) for v in by_status.values())} entries)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--type", choices=["D", "E", "Q"])
    args = ap.parse_args()

    types = [args.type] if args.type else ["D", "E", "Q"]
    for t in types:
        build_index_for(t)


if __name__ == "__main__":
    main()
