#!/usr/bin/env python3
"""Regenerate docs/atlas/journal/_index.md from all journal entries.

The index is a human-only browse view (the agent reads frontmatter directly
via orient). Its content depends solely on entry frontmatter — never on the
run date — so identical data always yields a byte-identical file; recency
windows are computed by orient at render time instead.

Usage:
    reindex.py

Must be run from project root (the directory containing docs/atlas/).
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml

ATLAS = Path("docs/atlas")
JOURNAL = ATLAS / "journal"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?(.*)$", re.DOTALL)


def parse_md(text):
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    meta = yaml.safe_load(m.group(1)) or {}
    return meta, m.group(2)


def collect_entries():
    if not JOURNAL.exists():
        return [], []
    active, closed = [], []
    for p in sorted(JOURNAL.glob("*.md")):
        if p.name.startswith("_"):
            continue
        meta, _ = parse_md(p.read_text(encoding="utf-8"))
        if not meta:
            continue
        if meta.get("status") == "active":
            active.append((meta, p))
        else:
            closed.append((meta, p))
    closed.sort(key=lambda x: x[0].get("date", ""), reverse=True)
    active.sort(key=lambda x: str(x[0].get("opened", x[0].get("date", ""))), reverse=True)
    return active, closed


def render_active(lines, active):
    lines.append(f"## Active ({len(active)})")
    lines.append("")
    if not active:
        lines.append("*No active entries.*")
        lines.append("")
        return
    for meta, p in active:
        tags = ", ".join(meta.get("tags") or []) or "(no tags)"
        opened = meta.get("opened", meta.get("date", "?"))
        lines.append(f"- **{meta.get('date', '?')}** [{p.stem}]({p.name})")
        lines.append(f"  - opened: {opened}")
        lines.append(f"  - tags: {tags}")
    lines.append("")


def render_by_tag(lines, closed):
    by_tag = defaultdict(list)
    for meta, p in closed:
        for tag in meta.get("tags") or []:
            by_tag[tag].append((meta, p))
    if not by_tag:
        return
    lines.append("## By tag (closed)")
    lines.append("")
    for tag in sorted(by_tag.keys()):
        entries = by_tag[tag]
        dates = [str(m.get("date", "?")) for m, _ in entries]
        lines.append(f"- **{tag}** ({len(entries)}): {', '.join(dates)}")
    lines.append("")


def render_by_month(lines, closed):
    by_month = defaultdict(list)
    for meta, p in closed:
        date_str = str(meta.get("date", ""))
        if len(date_str) >= 7:
            by_month[date_str[:7]].append((meta, p))
    if not by_month:
        return
    lines.append("## By month (archive)")
    lines.append("")
    for month in sorted(by_month.keys(), reverse=True):
        entries = by_month[month]
        lines.append(f"### {month} ({len(entries)} entries)")
        for meta, p in entries:
            lines.append(f"- {meta.get('date', '?')} [{p.stem}]({p.name})")
        lines.append("")


def main():
    if not JOURNAL.exists():
        print("docs/atlas/journal/ does not exist; nothing to index")
        return
    active, closed = collect_entries()

    lines = [
        "# Journal Index",
        "",
        "> Auto-generated by `atlas-log/scripts/reindex.py`. Do not edit by hand.",
        "",
    ]
    render_active(lines, active)
    render_by_tag(lines, closed)
    render_by_month(lines, closed)

    output = "\n".join(lines).rstrip() + "\n"
    (JOURNAL / "_index.md").write_text(output, encoding="utf-8")
    print(f"reindexed {JOURNAL / '_index.md'} ({len(active)} active, {len(closed)} closed)")


if __name__ == "__main__":
    main()
